FROM ruby:3.4.8-alpine

RUN apk add --no-cache \
    build-base \
    postgresql-dev \
    tzdata \
    git \
    gcompat \
    yaml-dev

WORKDIR /app

COPY Gemfile ./
RUN bundle config set --local force_ruby_platform true && \
    bundle install

COPY . .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
